//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.11.08 at 08:22:49 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://sw.gmit.ie/ds/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ie.gmit.sw.G00341457_DS;
